name: Deploy Vithal Vision

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Update production folder
        shell: powershell
        run: |
          cd C:\vithal\vithal-vision
          git pull origin main

      - name: Install dependencies
        shell: powershell
        run: |
          cd C:\vithal\vithal-vision
          npm ci

      - name: Build the website
        shell: powershell
        run: |
          cd C:\vithal\vithal-vision
          npm run build

      - name: Debug runner
        shell: powershell
        run: |
          whoami
          $env:PATH
          where.exe pm2

      - name: Restart the live website
        shell: powershell
        run: |
          & "C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd" restart vithal-vision