name: Deploy Vithal Vision

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the website
        run: npm run build

      - name: Restart the live website
        shell: powershell
        run: |
         & "C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd" restart vithal-vision